<a href="https://colab.research.google.com/github/arifsl65/myfirstgit/blob/main/Entire_US_stock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url= 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSf2lI1ySZVYqgfY4hR56gx6_EomF9T6uS4Ji6RhkG53vmmwpqoHJ4Fmz-zDqgcoz_zgZu9G9p_LOtZ/pub?output=csv'

In [3]:
df=pd.read_csv(url)

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df

,Symbol,Company Name,Industry,Market Cap
0,A,"Agilent Technologies, Inc.",Diagnostics & Research,37648896000
1,AA,Alcoa Corporation,Aluminum,4784822272
2,AACG,ATA Creativity Global,Education & Training Services,25435134
3,AACI,Armada Acquisition Corp. I,Shell Companies,87025320
4,AACT,Ares Acquisition Corporation II,Shell Companies,639444992
...,...,...,...,...
5720,ZVRA,"Zevra Therapeutics, Inc.",Biotechnology,159693584
5721,ZVSA,"ZyVersa Therapeutics, Inc.",Biotechnology,2615280
5722,ZWS,Zurn Elkay Water Solutions Corporation,Pollution & Treatment Controls,5161864704
5723,ZYME,Zymeworks Inc.,Biotechnology,635268160
5724,ZYXI,"Zynex, Inc.",Medical Distribution,282387232

In [6]:
df.rename(columns={'Company Name': 'CompanyName'}, inplace=True)

In [7]:
df.rename(columns={'Market Cap': 'MarketCap'}, inplace=True)

In [8]:
df['Symbol'] = df['Symbol'].astype(str)

In [9]:
df['CompanyName'] = df['CompanyName'].astype(str)
df['Industry'] = df['Industry'].astype(str)

In [10]:
df['Industry'] = df['Industry'].astype(str)

In [11]:
df['MarketCap'] = df['MarketCap'].astype(int)

In [12]:
df.describe

<bound method NDFrame.describe of      Symbol                             CompanyName  \
0         A              Agilent Technologies, Inc.
1        AA                       Alcoa Corporation
2      AACG                   ATA Creativity Global
3      AACI              Armada Acquisition Corp. I
4      AACT         Ares Acquisition Corporation II
...     ...                                     ...
5720   ZVRA                Zevra Therapeutics, Inc.
5721   ZVSA              ZyVersa Therapeutics, Inc.
5722    ZWS  Zurn Elkay Water Solutions Corporation
5723   ZYME                          Zymeworks Inc.
5724   ZYXI                             Zynex, Inc.

                            Industry    MarketCap
0             Diagnostics & Research  37648896000
1                           Aluminum   4784822272
2      Education & Training Services     25435134
3                    Shell Companies     87025320
4                    Shell Companies    639444992
...                              ...          ...
5720                   Biotechnology    159693584
5721                   Biotechnology      2615280
5722  Pollution & Treatment Controls   5161864704
5723                   Biotechnology    635268160
5724            Medical Distribution    282387232

[5725 rows x 4 columns]>

In [13]:
print(df)

     Symbol                             CompanyName  \
0         A              Agilent Technologies, Inc.
1        AA                       Alcoa Corporation
2      AACG                   ATA Creativity Global
3      AACI              Armada Acquisition Corp. I
4      AACT         Ares Acquisition Corporation II
...     ...                                     ...
5720   ZVRA                Zevra Therapeutics, Inc.
5721   ZVSA              ZyVersa Therapeutics, Inc.
5722    ZWS  Zurn Elkay Water Solutions Corporation
5723   ZYME                          Zymeworks Inc.
5724   ZYXI                             Zynex, Inc.

                            Industry    MarketCap
0             Diagnostics & Research  37648896000
1                           Aluminum   4784822272
2      Education & Training Services     25435134
3                    Shell Companies     87025320
4                    Shell Companies    639444992
...                              ...          ...
5720                   Biotechnology    159693584
5721                   Biotechnology      2615280
5722  Pollution & Treatment Controls   5161864704
5723                   Biotechnology    635268160
5724            Medical Distribution    282387232

[5725 rows x 4 columns]

In [14]:
from google.colab import files

In [15]:
df.to_csv('output_file.csv', index=False)

In [16]:
def add_single_quotes(value):
    return f"'{value}'"

# Apply the function to each element in the DataFrame
df_with_quotes = df.applymap(add_single_quotes)

In [17]:
df_with_quotes

,Symbol,CompanyName,Industry,MarketCap
0,'A',"'Agilent Technologies, Inc.'",'Diagnostics & Research','37648896000'
1,'AA','Alcoa Corporation','Aluminum','4784822272'
2,'AACG','ATA Creativity Global','Education & Training Services','25435134'
3,'AACI','Armada Acquisition Corp. I','Shell Companies','87025320'
4,'AACT','Ares Acquisition Corporation II','Shell Companies','639444992'
...,...,...,...,...
5720,'ZVRA',"'Zevra Therapeutics, Inc.'",'Biotechnology','159693584'
5721,'ZVSA',"'ZyVersa Therapeutics, Inc.'",'Biotechnology','2615280'
5722,'ZWS','Zurn Elkay Water Solutions Corporation','Pollution & Treatment Controls','5161864704'
5723,'ZYME','Zymeworks Inc.','Biotechnology','635268160'
5724,'ZYXI',"'Zynex, Inc.'",'Medical Distribution','282387232'

In [18]:
df.to_csv('output_file.csv', index=False)

In [19]:
df_with_quotes.to_csv('stock_file.csv', index=False)

In [20]:
files.download('stock_file.csv')

In [25]:
df_with_quotes.loc[0]

Symbol                                  'A'
CompanyName    'Agilent Technologies, Inc.'
Industry           'Diagnostics & Research'
MarketCap                     '37648896000'
Name: 0, dtype: object

In [26]:

df = pd.DataFrame(df_with_quotes)

# Format the DataFrame with parentheses
formatted_df = df.apply(lambda col: f"('{col['Symbol']}', '{col['CompanyName']}', '{col['Industry']}', '{col['MarketCap']}')", axis=1)

# Print the formatted DataFrame
print(formatted_df)

0       (''A'', ''Agilent Technologies, Inc.'', ''Diag...
1       (''AA'', ''Alcoa Corporation'', ''Aluminum'', ...
2       (''AACG'', ''ATA Creativity Global'', ''Educat...
3       (''AACI'', ''Armada Acquisition Corp. I'', ''S...
4       (''AACT'', ''Ares Acquisition Corporation II''...
                              ...
5720    (''ZVRA'', ''Zevra Therapeutics, Inc.'', ''Bio...
5721    (''ZVSA'', ''ZyVersa Therapeutics, Inc.'', ''B...
5722    (''ZWS'', ''Zurn Elkay Water Solutions Corpora...
5723    (''ZYME'', ''Zymeworks Inc.'', ''Biotechnology...
5724    (''ZYXI'', ''Zynex, Inc.'', ''Medical Distribu...
Length: 5725, dtype: object

In [27]:
df.loc[0]

Symbol                                  'A'
CompanyName    'Agilent Technologies, Inc.'
Industry           'Diagnostics & Research'
MarketCap                     '37648896000'
Name: 0, dtype: object

In [28]:
formatted_df.loc[0]

"(''A'', ''Agilent Technologies, Inc.'', ''Diagnostics & Research'', ''37648896000'')"

In [29]:
formatted_df.to_csv('formatted_data.csv', index=False)

In [30]:
files.download('formatted_data.csv')

In [32]:
def format_row(row):
    return f"({row['Symbol']} , {row['CompanyName']} , {row['Industry']} , {row['MarketCap']})"

# Apply the function to each row using the apply method
df['FormattedData'] = df.apply(format_row, axis=1)

# Print the resulting DataFrame
print(df[['FormattedData']])

                                          FormattedData
0     ('A' , 'Agilent Technologies, Inc.' , 'Diagnos...
1     ('AA' , 'Alcoa Corporation' , 'Aluminum' , '47...
2     ('AACG' , 'ATA Creativity Global' , 'Education...
3     ('AACI' , 'Armada Acquisition Corp. I' , 'Shel...
4     ('AACT' , 'Ares Acquisition Corporation II' , ...
...                                                 ...
5720  ('ZVRA' , 'Zevra Therapeutics, Inc.' , 'Biotec...
5721  ('ZVSA' , 'ZyVersa Therapeutics, Inc.' , 'Biot...
5722  ('ZWS' , 'Zurn Elkay Water Solutions Corporati...
5723  ('ZYME' , 'Zymeworks Inc.' , 'Biotechnology' ,...
5724  ('ZYXI' , 'Zynex, Inc.' , 'Medical Distributio...

[5725 rows x 1 columns]

In [33]:
df[['FormattedData']].to_csv('formatted_data.csv', index=False)

In [34]:
files.download('formatted_data.csv')